include: package:pedantic/analysis_options.yaml

analyzer:
  language:
    strict-raw-types: true
  strong-mode:
    implicit-casts: false
  errors: 
    return_of_invalid_type: false
    argument_type_not_assignable: false
    curly_braces_in_flow_control_structures: false
    prefer_single_quotes: false
    prefer_double_quotes: error
    unnecessary_null_checks: error
    avoid_print: info
    directives_ordering: error
    camel_case_types: error
    non_constant_identifier_names: error

linter:
  rules:
    - cancel_subscriptions
    - avoid_function_literals_in_foreach_calls
    - avoid_setters_without_getters
    - no_runtimeType_toString
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_double_quotes
    - prefer_expression_function_bodies
    - prefer_final_locals
    - prefer_is_not_operator
    - provide_deprecation_message
    - type_init_formals
    - unnecessary_null_checks
    - avoid_print
    - empty_statements
    - directives_ordering
    - camel_case_types
    - non_constant_identifier_names