name: Dartbot
environment:
  sdk: ">=2.14.1 <3.0.0"
dependencies:
  crypto: ^3.0.1
  dart_ping: ^6.1.1
  dio: ^4.0.0
  dotenv: ^3.0.0
  image: ^3.0.8
  path: ^1.8.0
  puppeteer: ^2.3.0
  system_info: ^1.0.1
  vklib: ^0.2.3
dev_dependencies: 
  pedantic: ^1.11.1
